spring:
  application:
    name: spring-security-oauth2-resource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_resource
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1



server:
  port: 8081
  servlet:
    context-path: /contents

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize   #用户授权
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token  #资源token地址 检验token是否有效

mybatis:
  type-aliases-package: com.hxr.entity
  mapper-locations: classpath:mapper/*.xml
